slight improvements

diff --git a/cmpopt b/cmpopt
--- a/cmpopt
+++ b/cmpopt
@@ -28,31 +28,7 @@
 
 set -eo pipefail
 
-WARN() {
-    echo "WARNING ($(basename $0)):" "$@" 1>&2
-}
-
-ERROR() {
-    echo "ERROR in $1 ($(basename $0)):" "${@:2}" 1>&2
-    false
-}
-
-TESTARGUMENTS() {
-    localhowmany() { echo $#; }
-    expectedargcount=$(localhowmany ${3-})
-    receivedargcount=$1    
-    unset localhowmany
-    if [ "${expectedargcount}" != "${receivedargcount}" ]; then
-        if [ "${expectedargcount}" = 0 ]; then
-            ERROR "function ${FUNCNAME[1]}" "requires no arguments, but got ${receivedargcount}, i.e.: $2 (from function ${FUNCNAME[2]})"
-        elif [ "${receivedargcount}" = 0 ]; then
-            ERROR "function ${FUNCNAME[1]}" "requires ${expectedargcount} arguments ($3), but got ${receivedargcount} (from ${FUNCNAME[2]})"
-        else
-            ERROR "function ${FUNCNAME[1]}" "requires ${expectedargcount} arguments ($3), but got ${receivedargcount}, i.e.: $2 (from ${FUNCNAME[2]})"
-        fi
-    fi
-}
-
+# catch help argument
 if [ "${1-}" = "-h" -o "${1-}" = "--help" ] ; then
     cat <<-EOF
 	'cmpopt' finds the compute and compilation environment 
@@ -77,7 +53,7 @@ if [ "${1-}" = "-h" -o "${1-}" = "--help" ] ; then
 	argument or the current shell, for the following variables:
 
 	  - Operating system and hardware properties:
-	      SYSTEMNAME SYSTEMVERSION OS OSVERSION CPU GPUS NVIDIADRIVERVERSION NVIDIACOMPUTECAPABILITY 
+	      SYSTEMNAME SYSTEMVERSION OS OSVERSION MACHINEARCH MACHINEVENDOR CPU GPUS NVIDIADRIVERVERSION NVIDIACOMPUTECAPABILITY 
 
 	  - C compiler and options:
 	      CC*  CFLAGS*  CFLAGSOPT  CCOMPILERVERSION  OPENMPCFLAGS  OPENMPCLDFLAGS 
@@ -90,19 +66,50 @@ if [ "${1-}" = "-h" -o "${1-}" = "--help" ] ; then
 	  - Fortran compiler and options:
 	      FC*  FFLAGS*  FORTRANCOMPILERVERSION  FFLAGSOPT  OPENMPFFLAGS  
 	      OPENMPFLDFLAGS  OPENMPGPUFFLAGS  OPENMPGPUFLDFLAGS  F77
-
-	  - Hardware properties compiler and options:
 	      
-
 	  - CUDA compiler and options
 	      CUDACXX*  CUDAFLAGS*  CUDAHOSTCXX*  CUDACOMPILERVERSION  CUDAHOSTCXXCOMPILERVERSION 
 	      CUDAFLAGSOPT  CUDAFLAGSOMP  CUDALINKFLAGSOMP
    
 	Note that if any of these variables are already set in the environment, 
-	'detectcomp' takes the values in the environment instead of detecting them.
+	'cmpopt' takes the values in the environment instead of detecting them.
 EOF
     exit 
 fi
+
+# helper functions
+
+WARN() {
+    # helper function to print warnings to standard error
+    echo "WARNING ($(basename $0)):" "$@" 1>&2
+}
+
+ERROR() {
+    # helper function to print error message to standard error
+    echo "ERROR in $1 ($(basename $0)):" "${@:2}" 1>&2
+    false # would do 'exit 1', but often called from subshells where that does not exit the whole script.
+}
+
+TESTARGUMENTS() {
+    # test if the number of arguments is correctly given to a bash
+    # function. That bash function should call this function as
+    #  TESTARGUMENT $# "$*" "argumentnames"
+    # where the argumentnames is one quoted string containing space
+    # separated names of the arguments.
+    localhowmany() { echo $#; }
+    expectedargcount=$(localhowmany ${3-})
+    receivedargcount=$1    
+    unset localhowmany
+    if [ "${expectedargcount}" != "${receivedargcount}" ]; then
+        if [ "${expectedargcount}" = 0 ]; then
+            ERROR "function ${FUNCNAME[1]}" "requires no arguments, but got ${receivedargcount}, i.e.: $2 (from function ${FUNCNAME[2]})"
+        elif [ "${receivedargcount}" = 0 ]; then
+            ERROR "function ${FUNCNAME[1]}" "requires ${expectedargcount} arguments ($3), but got ${receivedargcount} (from ${FUNCNAME[2]})"
+        else
+            ERROR "function ${FUNCNAME[1]}" "requires ${expectedargcount} arguments ($3), but got ${receivedargcount}, i.e.: $2 (from ${FUNCNAME[2]})"
+        fi
+    fi
+}
 
 # Functions to detect various aspects of the compilation environment
 
@@ -523,9 +530,9 @@ detectcflagsopt() {
 
 detectcxxflagsopt() {
     TESTARGUMENTS $# "$*" "cxxcompiler cxxcompilerversion cpu" 
-    local cxxompiler=$1
+    local cxxcompiler=$1
     local cxxompilerversion=$2
-    local cpu=$3
+    local cpu=$3    
     case $(basename "${cxxcompiler}") in
         core-g++|g++)                     detectcflagsopt gcc     "${cxxcompilerversion}" "${cpu}" ;;
         icpc)                             detectcflagsopt icc     "${cxxcompilerversion}" "${cpu}" ;;
